services:
  - type: web
    name: epl-flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: epl_db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.9

databases:
  - name: epl_db
    plan: free
